#!/bin/bash

TMP_CACHE_DIR="/tmp/eporal-manager"
DEBUG=false
REDIRECT_OUTPUT="/dev/stdout"
REDIRECT_ERROR="/dev/stderr"
if [[ $DEBUG == false ]]; then
	REDIRECT_OUTPUT="/dev/null"
	REDIRECT_ERROR="/dev/null"
fi

eportal_login()
{
	EPORTAL_USER=$1
	EPORTAL_PWD=$2
	_RET_VAL=$3

	if [[ $EPORTAL_USER && $EPORTAL_PWD ]]; then
		rm -r $TMP_CACHE_DIR 1>${REDIRECT_OUTPUT} 2>${REDIRECT_ERROR}
		echo "Logging in..."
		wget http://www.bing.com/ -P $TMP_CACHE_DIR  1>${REDIRECT_OUTPUT} 2>${REDIRECT_ERROR}
		raw_html=`cat $TMP_CACHE_DIR/index.html`

		if [[ ${raw_html:0:8} != "<script>" ]]; then
			echo "Already login."
		else
			portal_url=`echo $raw_html | sed -s "s/^<script>top.self.location.href='\(.*\)'<\/script>\(.*\)/\1/"`
			login_url=`echo "$portal_url&username=$EPORTAL_USER&pwd=$EPORTAL_PWD" | sed -s "s/\(.*\)index.jsp?\(.*\)/\1webGateModeV2.do?method=login\&\2/"`
			#echo $login_url
			wget $login_url -P $TMP_CACHE_DIR  1>${REDIRECT_OUTPUT} 2>${REDIRECT_ERROR}
			wget $login_url -P $TMP_CACHE_DIR  1>${REDIRECT_OUTPUT} 2>${REDIRECT_ERROR}
			rm -r $TMP_CACHE_DIR

			wget http://www.bing.com/ -P $TMP_CACHE_DIR  1>${REDIRECT_OUTPUT} 2>${REDIRECT_ERROR}
			raw_html=`cat $TMP_CACHE_DIR/index.html`
			if [[ ${raw_html:0:8} != "<script>" ]]; then
				echo "Login."
			else
				echo "Fail to login."
			fi
		fi

		rm -r $TMP_CACHE_DIR
		eval $_RET_VAL=1
	else
		eval $_RET_VAL=0
	fi
}

print_usage()
{
	echo "Usage: $0 [login|link|logout|drop] [username] [password]"
}

case $1 in
	login|link)
		eportal_login $2 $3 result
		if (( $result == 0 )); then
			print_usage
			exit 3
		fi
	;;
	logout|drop)
		echo "Not yet"
		exit 3
	;;
	*|"")
		print_usage
		exit 3
	;;
esac

:

