#!/bin/bash

eportal_login()
{
	EPORTAL_USER=$1
	EPORTAL_PWD=$2
	_RET_VAL=$3

	if [[ $EPORTAL_USER && $EPORTAL_PWD ]]; then
		rm -r /tmp/netstuff 1>/dev/null 2>&1
		echo "Logging in..."
		wget http://www.bing.com/ -P /tmp/netstuff 1>/dev/null 2>&1
		raw_html=`cat /tmp/netstuff/index.html`

		if [[ ${raw_html:0:8} != "<script>" ]]; then
			echo "Already login."
		else
			portal_url=`echo $raw_html | sed -s "s/^<script>top.self.location.href='\(.*\)'<\/script>\(.*\)/\1/"`
			login_url=`echo "$portal_url&username=$EPORTAL_USER&pwd=$EPORTAL_PWD" | sed -s "s/\(.*\)index.jsp?\(.*\)/\1webGateModeV2.do?method=login\&\2/"`
			#echo $login_url
			wget $login_url -P /tmp/netstuff 1>/dev/null 2>&1
			wget $login_url -P /tmp/netstuff 1>/dev/null 2>&1
			rm -r /tmp/netstuff

			wget http://www.bing.com/ -P /tmp/netstuff 1>/dev/null 2>&1
			raw_html=`cat /tmp/netstuff/index.html`
			if [[ ${raw_html:0:8} != "<script>" ]]; then
				echo "Login."
			else
				echo "Fail to login."
			fi
		fi

		rm -r /tmp/netstuff
		eval $_RET_VAL=1
	else
		eval $_RET_VAL=0
	fi
}

print_usage()
{
	echo "Usage: $0 [login|link|logout|drop] [username] [password]"
}

case $1 in
	login|link)
		eportal_login $2 $3 result
		if (( $result == 0 )); then
			print_usage
			exit 3
		fi
	;;
	logout|drop)
		echo "Not yet"
		exit 3
	;;
	*|"")
		print_usage
		exit 3
	;;
esac

:

